# Checklist padrão da disciplina: os 30 critérios do Relatório de Teste de Usabilidade.
from .criterios_especiais import (
    _achados_rastreaveis, _estrutura_segue_template, _evidencia_sustenta_resultado,
    _fonte_citada_nas_referencias, _heuristicas_de_nielsen, _identificadores_de_tarefa_coincidem,
    _quantitativos_coincidem,
)
from .verificadores import combinado, contagem_regex, regex, sem_marcadores_de_template, termos

CRITERIOS = [
    {"codigo": "U01", "categoria": "Introdução e contexto",
     "descricao": "O contexto caracteriza o sistema web avaliado?",
     "verificar": combinado(termos("contexto do projeto"),
                            regex(r"(publico[- ]?alvo|endereco eletronico|\bhttp|www\.)", "público-alvo/endereço do sistema"))},
    {"codigo": "U02", "categoria": "Introdução e contexto",
     "descricao": "A justificativa para a escolha do sistema foi apresentada?",
     "verificar": regex(r"(justificativ[ae]\s+(da|para|pela)\s+escolha|motivo\s+da\s+escolha|"
                        r"escolhid[oa]\s+(pois|porque|por)|raz[aã]o\s+da\s+escolha|"
                        r"crit[eé]rio\s+de\s+escolha|por\s+(isso|essa\s+raz[aã]o)[, ]+(foi\s+)?escolhid)",
                        "justificativa explícita da escolha do sistema")},
    {"codigo": "U03", "categoria": "Introdução e contexto",
     "descricao": "Os objetivos específicos do teste foram descritos?",
     "verificar": termos("objetivos do teste", "objetivo do teste", "objetivos especificos")},
    {"codigo": "U04", "categoria": "Introdução e contexto",
     "descricao": "O aspecto de qualidade avaliado foi identificado?",
     "verificar": termos("usabilidade")},
    {"codigo": "U05", "categoria": "Metodologia e planejamento",
     "descricao": "As tarefas planejadas para os participantes foram listadas?",
     "verificar": combinado(termos("planejamento do teste"), termos("tarefa", "cenario"))},
    {"codigo": "U06", "categoria": "Metodologia e planejamento",
     "descricao": "Cada tarefa indica uma heurística de Nielsen?",
     "verificar": contagem_regex(r"heuristica", 3, "menções a heurística associada às tarefas")},
    {"codigo": "U07", "categoria": "Metodologia e planejamento",
     "descricao": "Cada tarefa possui um cenário de uso definido?",
     "verificar": termos("cenario")},
    {"codigo": "U08", "categoria": "Metodologia e planejamento",
     "descricao": "Cada tarefa identifica a interface avaliada?",
     "verificar": termos("interface")},
    {"codigo": "U09", "categoria": "Metodologia e planejamento",
     "descricao": "A aplicação da técnica de caixa preta foi explicada?",
     "verificar": termos("caixa preta", "tecnica de teste utilizada", "black box")},
    {"codigo": "U10", "categoria": "Metodologia e planejamento",
     "descricao": "A relevância da técnica de caixa preta para o teste foi justificada?",
     "verificar": combinado(termos("caixa preta", "black box"),
                            regex(r"(relevanci|importante para|contribui para)", "relevância da técnica"))},
    {"codigo": "U11", "categoria": "Metodologia e planejamento",
     "descricao": "Os recursos utilizados no teste foram identificados?",
     "verificar": termos("ferramentas e recursos", "ferramentas utilizadas", "gravacao de tela", "software especifico")},
    {"codigo": "U12", "categoria": "Execução do teste",
     "descricao": "O processo de execução do teste foi descrito?",
     "verificar": termos("processo de teste e resultados", "execucao do teste", "processo de execucao")},
    {"codigo": "U13", "categoria": "Execução do teste",
     "descricao": "Cada tarefa planejada possui um resultado registrado?",
     "verificar": termos("resultado")},
    {"codigo": "U14", "categoria": "Execução do teste",
     "descricao": "Cada tarefa executada possui uma evidência verificável?",
     "verificar": termos("evidencia", "print", "captura de tela", "imagem")},
    {"codigo": "U15", "categoria": "Execução do teste",
     "descricao": "Cada evidência sustenta o resultado atribuído à tarefa?",
     "verificar": _evidencia_sustenta_resultado},
    {"codigo": "U16", "categoria": "Análise de usabilidade",
     "descricao": "A análise contempla as dez heurísticas de Nielsen?",
     "verificar": _heuristicas_de_nielsen},
    {"codigo": "U17", "categoria": "Análise de usabilidade",
     "descricao": "Os achados da análise são rastreáveis aos testes executados?",
     "verificar": _achados_rastreaveis},
    {"codigo": "U18", "categoria": "Análise de usabilidade",
     "descricao": "Os problemas de maior impacto foram identificados?",
     "verificar": termos("problemas criticos", "problemas de maior impacto", "principais problemas")},
    {"codigo": "U19", "categoria": "Análise de usabilidade",
     "descricao": "Cada problema de maior impacto possui uma classificação?",
     "verificar": combinado(termos("problemas criticos", "problemas de maior impacto", "principais problemas"),
                            contagem_regex(r"\b(alto|alta|medio|media|baixo|baixa)\b", 2, "níveis de impacto classificados"))},
    {"codigo": "U20", "categoria": "Conclusão e recomendações",
     "descricao": "A conclusão sintetiza a avaliação geral da qualidade do sistema?",
     "verificar": termos("conclusao geral", "conclusao")},
    {"codigo": "U21", "categoria": "Conclusão e recomendações",
     "descricao": "As recomendações decorrem dos problemas identificados?",
     "verificar": termos("recomendacoes de melhoria", "recomendacao")},
    {"codigo": "U22", "categoria": "Checklist do processo",
     "descricao": "O checklist registra as etapas previstas do processo de teste?",
     "verificar": combinado(termos("checklist do processo"),
                            contagem_regex(r"(planejamento|preparacao|execucao|analise|revisao)", 4, "etapas do processo"))},
    {"codigo": "U23", "categoria": "Checklist do processo",
     "descricao": "O responsável pela aplicação do checklist foi identificado?",
     "verificar": termos("aplicado por", "responsavel pela aplicacao")},
    {"codigo": "U24", "categoria": "Checklist do processo",
     "descricao": "O responsável pela revisão do checklist foi identificado?",
     "verificar": termos("revisado por", "responsavel pela revisao")},
    {"codigo": "U25", "categoria": "Referências",
     "descricao": "A fonte utilizada para as heurísticas de Nielsen foi citada?",
     "verificar": _fonte_citada_nas_referencias("nielsen")},
    {"codigo": "U26", "categoria": "Referências",
     "descricao": "A fonte utilizada para a técnica de caixa preta foi citada?",
     "verificar": _fonte_citada_nas_referencias("caixa preta", "black box", "istqb", "teste funcional")},
    {"codigo": "U27", "categoria": "Consistência documental",
     "descricao": "A estrutura do documento segue a ordem definida no template?",
     "verificar": _estrutura_segue_template},
    {"codigo": "U28", "categoria": "Consistência documental",
     "descricao": "Os textos de orientação do template foram removidos da versão avaliada?",
     "verificar": sem_marcadores_de_template},
    {"codigo": "U29", "categoria": "Consistência documental",
     "descricao": "Os identificadores das tarefas coincidem entre planejamento e execução?",
     "verificar": _identificadores_de_tarefa_coincidem},
    {"codigo": "U30", "categoria": "Consistência documental",
     "descricao": "Os quantitativos apresentados na análise coincidem com os resultados da execução?",
     "verificar": _quantitativos_coincidem},
]

NOME = "Relatório de Teste de Usabilidade"
