# Checklist padrão da disciplina: os 30 critérios do Relatório de Teste de Usabilidade.
CRITERIOS = [
    {"codigo": "U01", "categoria": "Introdução e contexto",
     "descricao": "O contexto caracteriza o sistema web avaliado?"},
    {"codigo": "U02", "categoria": "Introdução e contexto",
     "descricao": "A justificativa para a escolha do sistema foi apresentada?"},
    {"codigo": "U03", "categoria": "Introdução e contexto",
     "descricao": "Os objetivos específicos do teste foram descritos?"},
    {"codigo": "U04", "categoria": "Introdução e contexto",
     "descricao": "O aspecto de qualidade avaliado foi identificado?"},
    {"codigo": "U05", "categoria": "Metodologia e planejamento",
     "descricao": "As tarefas planejadas para os participantes foram listadas?"},
    {"codigo": "U06", "categoria": "Metodologia e planejamento",
     "descricao": "Cada tarefa indica uma heurística de Nielsen?"},
    {"codigo": "U07", "categoria": "Metodologia e planejamento",
     "descricao": "Cada tarefa possui um cenário de uso definido?"},
    {"codigo": "U08", "categoria": "Metodologia e planejamento",
     "descricao": "Cada tarefa identifica a interface avaliada?"},
    {"codigo": "U09", "categoria": "Metodologia e planejamento",
     "descricao": "A aplicação da técnica de caixa preta foi explicada?"},
    {"codigo": "U10", "categoria": "Metodologia e planejamento",
     "descricao": "A relevância da técnica de caixa preta para o teste foi justificada?"},
    {"codigo": "U11", "categoria": "Metodologia e planejamento",
     "descricao": "Os recursos utilizados no teste foram identificados?"},
    {"codigo": "U12", "categoria": "Execução do teste",
     "descricao": "O processo de execução do teste foi descrito?"},
    {"codigo": "U13", "categoria": "Execução do teste",
     "descricao": "Cada tarefa planejada possui um resultado registrado?"},
    {"codigo": "U14", "categoria": "Execução do teste",
     "descricao": "Cada tarefa executada possui uma evidência verificável?"},
    {"codigo": "U15", "categoria": "Execução do teste",
     "descricao": "Cada evidência sustenta o resultado atribuído à tarefa?"},
    {"codigo": "U16", "categoria": "Análise de usabilidade",
     "descricao": "A análise contempla as dez heurísticas de Nielsen?"},
    {"codigo": "U17", "categoria": "Análise de usabilidade",
     "descricao": "Os achados da análise são rastreáveis aos testes executados?"},
    {"codigo": "U18", "categoria": "Análise de usabilidade",
     "descricao": "Os problemas de maior impacto foram identificados?"},
    {"codigo": "U19", "categoria": "Análise de usabilidade",
     "descricao": "Cada problema de maior impacto possui uma classificação?"},
    {"codigo": "U20", "categoria": "Conclusão e recomendações",
     "descricao": "A conclusão sintetiza a avaliação geral da qualidade do sistema?"},
    {"codigo": "U21", "categoria": "Conclusão e recomendações",
     "descricao": "As recomendações decorrem dos problemas identificados?"},
    {"codigo": "U22", "categoria": "Checklist do processo",
     "descricao": "O checklist registra as etapas previstas do processo de teste?"},
    {"codigo": "U23", "categoria": "Checklist do processo",
     "descricao": "O responsável pela aplicação do checklist foi identificado?"},
    {"codigo": "U24", "categoria": "Checklist do processo",
     "descricao": "O responsável pela revisão do checklist foi identificado?"},
    {"codigo": "U25", "categoria": "Referências",
     "descricao": "A fonte utilizada para as heurísticas de Nielsen foi citada?"},
    {"codigo": "U26", "categoria": "Referências",
     "descricao": "A fonte utilizada para a técnica de caixa preta foi citada?"},
    {"codigo": "U27", "categoria": "Consistência documental",
     "descricao": "A estrutura do documento segue a ordem definida no template?"},
    {"codigo": "U28", "categoria": "Consistência documental",
     "descricao": "Os textos de orientação do template foram removidos da versão avaliada?"},
    {"codigo": "U29", "categoria": "Consistência documental",
     "descricao": "Os identificadores das tarefas coincidem entre planejamento e execução?"},
    {"codigo": "U30", "categoria": "Consistência documental",
     "descricao": "Os quantitativos apresentados na análise coincidem com os resultados da execução?"},
]

NOME = "Relatório de Teste de Usabilidade"
